# Generated by Django 4.2.11 on 2024-04-17 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_tournaments',
            field=models.PositiveIntegerField(default=0, verbose_name='Total number of tournaments'),
        ),
        migrations.AddField(
            model_name='user',
            name='tournaments_wins',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of tournaments wins'),
        ),
    ]
