# Generated by Django 4.2.11 on 2024-04-17 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_total_tournaments_user_tournaments_wins'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mailValidate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
