# Generated by Django 4.2.11 on 2024-04-14 07:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_is_active_user_last_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='invites',
            field=models.ManyToManyField(related_name='sent_invites', to=settings.AUTH_USER_MODEL),
        ),
    ]
