version: '3.9'

services:

  postgresql:
    container_name: postgresql
    networks:
        - Transcendence
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 2s
      retries: 10

  adminer:
    container_name: postgre_adminer
    networks:
        - Transcendence
    image: adminer
    restart: always
    ports:
      - 8080:8080

  django:
    container_name: django
    networks:
        - Transcendence
    build: 
      context: .
      dockerfile: ./Django/Dockerfile.django  # Assure-toi d'avoir un Dockerfile pour Django
    ports:
      - "8000:8000"
    volumes:
      - ./test:/app  # Montage du répertoire du projet Django dans le conteneur
    depends_on:
      postgresql:
        condition: service_healthy

  nginx:
    container_name: nginx
    networks:
        - Transcendence
    build: 
      context: .
      dockerfile: ./nginx/Dockerfile.nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - django


networks:
    Transcendence:
        driver: bridge
