# Generated by Django 4.2.11 on 2024-03-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0003_customuser_historique_resultats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='historique_resultats',
            field=models.JSONField(default=list, verbose_name='Historique des Résultats'),
        ),
    ]
