# Generated by Django 4.2.11 on 2024-03-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0002_customuser_date_joined_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='historique_resultats',
            field=models.TextField(blank=True, verbose_name='Historique des Résultats'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='nombre_defaites',
            field=models.PositiveIntegerField(default=0, verbose_name='Nombre de Défaites'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='nombre_victoires',
            field=models.PositiveIntegerField(default=0, verbose_name='Nombre de Victoires'),
        ),
    ]
