# Generated by Django 4.2.11 on 2024-04-09 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournament', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('ballwidth', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('planksize', models.DecimalField(decimal_places=2, default=30, max_digits=5)),
                ('Speed', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('acceleration', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('winpoint', models.PositiveIntegerField(default=5)),
                ('gamemode', models.PositiveIntegerField(default=0)),
                ('gameRunning', models.BooleanField(default=False)),
                ('gameLevel', models.PositiveIntegerField(default=0)),
                ('levelPos', models.PositiveIntegerField(default=0)),
                ('nextGame', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.game')),
                ('tournament', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tournament.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='GameUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('game', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
