# Generated by Django 4.2.11 on 2024-03-26 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('gameLevel', models.PositiveIntegerField(default=0)),
                ('ballSize', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('raquetSize', models.DecimalField(decimal_places=2, default=30, max_digits=5)),
                ('gameSpeed', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('gameAcceleration', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('winPoint', models.PositiveIntegerField(default=5)),
                ('gameMode', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GameUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
