# Generated by Django 4.2.11 on 2024-03-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='players',
        ),
        migrations.RemoveField(
            model_name='game',
            name='tournament',
        ),
        migrations.RemoveField(
            model_name='gameuser',
            name='game',
        ),
        migrations.AddField(
            model_name='game',
            name='ballSize',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5),
        ),
        migrations.AddField(
            model_name='game',
            name='gameAcceleration',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
        migrations.AddField(
            model_name='game',
            name='gameMode',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='gameSpeed',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
        migrations.AddField(
            model_name='game',
            name='raquetSize',
            field=models.DecimalField(decimal_places=2, default=30, max_digits=5),
        ),
        migrations.AddField(
            model_name='game',
            name='winPoint',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='gameLevel',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
