# Generated by Django 4.2.11 on 2024-04-10 13:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_game_ballwidth_alter_game_planksize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='Speed',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0.05), django.core.validators.MaxValueValidator(0.3)]),
        ),
        migrations.AlterField(
            model_name='game',
            name='acceleration',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(0.1)]),
        ),
        migrations.AlterField(
            model_name='game',
            name='ballwidth',
            field=models.FloatField(default=0.1, validators=[django.core.validators.MinValueValidator(0.05), django.core.validators.MaxValueValidator(0.3)]),
        ),
        migrations.AlterField(
            model_name='game',
            name='gamemode',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='game',
            name='planksize',
            field=models.FloatField(default=0.3, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(0.4)]),
        ),
        migrations.AlterField(
            model_name='game',
            name='winpoint',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(15)]),
        ),
        migrations.AlterField(
            model_name='gameuser',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
