# Generated by Django 4.2.11 on 2024-03-26 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_remove_game_players_remove_game_tournament_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='gameSpeed',
            new_name='Speed',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='gameAcceleration',
            new_name='acceleration',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='ballSize',
            new_name='ballwidth',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='gameMode',
            new_name='gamemode',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='raquetSize',
            new_name='planksize',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='winPoint',
            new_name='winpoint',
        ),
    ]
